name: Build All
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
      - cron: '30 0/6 * * *'

jobs:
  build-amd64:
    uses: ./.github/workflows/build.yaml
    with:
      runner: ubuntu-24.04
      arch: amd64
      max-task: ${{vars.MAX_TASK || 10}}
  build-arm64:
    uses: ./.github/workflows/build.yaml
    with:
      runner: ubuntu-24.04-arm
      arch: arm64
      max-task: ${{vars.MAX_TASK || 10}}
