name: Build All
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      max-tasks:
        type: number
        description: "最大任务数"
        required: false
        default: 10
      max-parallel:
        type: number
        description: '最大并行数'
        required: false
        default: 64
      debug:
        type: boolean
        description: "启用调试"
        required: false
        default: false
  schedule:
    - cron: "30 0/6 * * *"

jobs:
  build-amd64:
    uses: ./.github/workflows/build.yaml
    with:
      runner: ubuntu-24.04
      arch: amd64
      max-tasks: ${{fromJSON(inputs.max-tasks|| vars.MAX_TASKS || '10')}}
      debug: ${{fromJSON(inputs.debug||vars.ENABLE_DEBUG||'false')}}
      max-parallel: ${{fromJSON(inputs.max-parallel||vars.MAX_PARALLEL||'64')}}
    secrets:
      FTP_URL: ${{secrets.FTP_URL}}
      SSH_URL: ${{secrets.SSH_URL}}
      SSH_HOST_KEY: ${{secrets.SSH_HOST_KEY}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      CF_PROXY: ${{secrets.CF_PROXY}}

  build-arm64:
    uses: ./.github/workflows/build.yaml
    with:
      runner: ubuntu-24.04-arm
      arch: arm64
      max-tasks: ${{fromJSON(inputs.max-tasks|| vars.MAX_TASKS || '10')}}
      debug: ${{fromJSON(inputs.debug||vars.ENABLE_DEBUG||'false')}}
      max-parallel: ${{fromJSON(inputs.max-parallel||vars.MAX_PARALLEL||'64')}}
    secrets:
      FTP_URL: ${{secrets.FTP_URL}}
      SSH_URL: ${{secrets.SSH_URL}}
      SSH_HOST_KEY: ${{secrets.SSH_HOST_KEY}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      CF_PROXY: ${{secrets.CF_PROXY}}
