name: Build All
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
      - cron: '30 0/6 * * *'

jobs:
  build-amd64:
    uses: .github/workflows/build.yml
    with:
      runner: ubuntu-24.04
      arch: amd64
  build-arm64:
    uses: .github/workflows/build.yml
    with:
      runner: ubuntu-24.04-arm
      arch: arm64