name: Build Cache
run-name: Build Cache
on:
  workflow_dispatch:
  schedule:
      - cron: '0 0 */7 * *'
jobs:
  cache:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64,arm64]
        base: ["org.deepin.base/23.1.0","org.deepin.foundation/20.0.0","org.deepin.foundation/23.0.0","com.uniontech.foundation/20.0.1"]
      fail-fast: false
    steps:
      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/linglong-builder/
          key: linglong-${{matrix.arch}}-${{matrix.base}}
      - name: Build Cache
        run: |
          XARGH=$ARCH
          case "$ARCH" in
          "amd64")
              XARGH="x86_64"
              ;;
          "arm64")
              XARGH="arm64"
              ;;
          esac
          make -f common/ostree.mk MODULE=binary ID="$CHANNEL:$BASE/$XARGH"
        env:
          BASE: ${{matrix.base}}
          ARCH: ${{matrix.arch}}
          CHANNEL: main