name: Index
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
      - cron: '0 0 * * *'
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Essentials
        run: |
          sudo apt update
          sudo apt install apt-file -y
      - name: Check
        id: check
        run: |
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          sudo sysctl -w user.max_user_namespaces=28633
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git submodule update --init --remote
          make index
          make push-index