name: Index
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
      - cron: '0 0 * * *'
jobs:
  check:
    runs-on: ${{matrix.runner}}
    strategy:
      max-parallel: 32
      matrix:
        include:
         - runner: ubuntu-24.04
           arch: amd64
         - runner: ubuntu-24.04-arm
           arch: arm64
      fail-fast: false
    env:
      ARCH: ${{matrix.arch}}
      RUNNER: ${{matrix.runner}}
      WORK_DIR: build/${{matrix.arch}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Essentials
        run: |
          sudo apt update
          sudo apt install apt-file -y
      - name: Init
        run: |
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          sudo sysctl -w user.max_user_namespaces=28633
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          git -C "$WORK_DIR" pull origin $ARCH --rebase
      - name: Check
        id: check
        run: |
          make index
      - name: Commit
        id: commit
        run: |
          cd "$WORK_DIR"
          git add index.csv
          git diff --cached --quiet || git commit -m "Update Index"
          git pull origin $ARCH --rebase && git push origin HEAD:$ARCH
      # - uses: valeriangalliat/action-sshd-cloudflared@v3
      #   if: failure()
