name: Index
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
      - cron: '0 0 * * *'
jobs:
  check:
    runs-on: ${{matrix.runner}}
    strategy:
      max-parallel: 32
      matrix:
        include:
         - runner: ubuntu-24.04
           arch: amd64
         - runner: ubuntu-24.04-arm
           arch: arm64
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Essentials
        run: |
          sudo apt update
          sudo apt install apt-file -y
      - name: Check
        id: check
        run: |
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          sudo sysctl -w user.max_user_namespaces=28633
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull origin $ARCH --rebase
          make index
          WORK_DIR="build/$ARCH"
          cd "$WORK_DIR"
          git add index.csv
          git diff --cached --quiet || git commit -m "Update Index"
          git pull origin $ARCH --rebase && git push origin HEAD:$ARCH
        env:
          ARCH: ${{matrix.arch}}
          RUNNER: ${{matrix.runner}}
      # - uses: valeriangalliat/action-sshd-cloudflared@v3
      #   if: failure()
